### PR TITLE
[Fix][CI] Fix moe_fused_topk test and remove unsound targeted scope

### LINKED ISSUE #973: [BUG][CI] fix broken moe_fused_topk tests and remove unsound targeted scope
### Symptom / Motivation

PR #970 (`[Refactor][Benchmark] Narrow gen_inputs return types across workload protocols`) unified all workload `gen_inputs()` to return tuples, but missed updating `tests/ops/test_moe_fused_topk.py`. This broke all 13 `test_fused_topk` cases on CI with:

```
AttributeError: 'tuple' object has no attribute 'to'
```

CI failure: https://github.com/tile-ai/TileOPs/actions/runs/24411551409/job/71309490631

Despite `gpu-smoke` being a required status check and **failing** on #970's PR, the PR was merged because the `tileops-review` team had `bypass_mode: pull_request` on the main branch ruleset (ID 8507572).

Separately, the CI targeted scope strategy (introduced in #510 on 2026-03-15) maps `tileops/ops/*.py` changes to only run the corresponding `tests/ops/test_<op>.py`. This is an unsound assumption — ops share code via kernels and utilities, so modifying one op can silently break tests for other ops.

### Root Cause Analysis

1. **Test bug**: `tests/ops/test_moe_fused_topk.py:84` calls `gating = test.gen_inputs()` but `gen_inputs()` now returns `(tensor,)` (a tuple), not a bare tensor. The subsequent `gating.to(torch.float32)` fails with `AttributeError`.

2. **Unsound CI scope**: `.github/workflows/gpu-smoke.yml` lines 270-281 map `tileops/ops/*.py` → targeted scope, running only `tests/ops/test_<op>.py`. This assumes ops are fully independent, which is false — ops share kernels, base classes, and utility code.

3. **Governance gap**: `tileops-review` team had bypass permission on the main branch ruleset, allowing merge with failing required checks. This bypass has been revoked via GitHub UI.

### Related Files

- `tests/ops/test_moe_fused_topk.py`
- `.github/workflows/gpu-smoke.yml`
- `workloads/moe.py`

## Goal

Fix the broken test, remove the unsound `tileops/ops/*.py` targeted scope so op code changes always trigger full-smoke, and document the governance fix (bypass revocation).

## Plan

1. Fix `tests/ops/test_moe_fused_topk.py:84`: change `gating = test.gen_inputs()` to `(gating,) = test.gen_inputs()`
2. Remove `tileops/ops/*.py` targeted mapping from `.github/workflows/gpu-smoke.yml` — op changes now fall through to `*` catch-all → `full-smoke`
3. Verify `tileops-review` bypass on ruleset 8507572 is revoked (done via GitHub UI, not code change)

## Constraints

- Do not modify `workloads/moe.py` — the tuple return type is correct per #970's protocol
- Targeted scope for `tests/ops/test_*.py`-only changes is retained (test files do not import each other)

## Acceptance Criteria

- [ ] AC-1: Modified files pass unit tests
- [ ] AC-2: All 13 `test_fused_topk` cases pass in CI gpu-smoke
- [ ] AC-3: `tileops/ops/*.py` changes trigger `full-smoke` scope (not `targeted`)
- [ ] AC-4: `tests/ops/test_*.py`-only changes still use `targeted` scope
- [ ] AC-5: Ruleset 8507572 `bypass_actors` is empty (no team can bypass required checks)

### PR DESCRIPTION
**Pull request by lcy-seso**
Closes #973

## Summary

- Fix `test_moe_fused_topk` broken by #970: unpack `gen_inputs()` tuple (`gating = test.gen_inputs()` → `(gating,) = test.gen_inputs()`)
- Remove unsound `tileops/ops/*.py` targeted scope from `gpu-smoke.yml`: op files share kernels and utilities, so mapping op changes to only the corresponding test file misses cross-op regressions. Op changes now fall through to `full-smoke`.
- Ruleset bypass for `tileops-review` team revoked via GitHub UI (not a code change)

## Test plan

- [ ] All 13 `test_fused_topk` cases pass in CI gpu-smoke
- [ ] `tileops/ops/*.py` changes trigger `full-smoke` scope
- [ ] `tests/ops/test_*.py`-only changes still use `targeted` scope

## Follow-up

- #974 — Review fork PR fast-path allowlist for `tileops/ops/*.py` (same unsound independence assumption)

### CODE REVIEW

**Review by Ibuki-wind — APPROVED** [review]
Clean fix: this call site now matches the tuple-based `gen_inputs()` contract from #970, and the touched test file stays node-neutral.

**Review by Ibuki-wind — APPROVED** [review]
Current head looks clean: the `gen_inputs()` unpack fix is correct and node-neutral, and the `gpu-smoke.yml` change makes op-file edits fall back to the conservative `full-smoke` path instead of relying on an unsound direct test mapping.
