### PR TITLE
[Fix][Benchmark] Restore failing softmax and FA3 paged decode bench cases in nightly

### PR DESCRIPTION
**Pull request by superAngGao**
## Summary

Restores **21 nightly benchmark cases** that were failing in [run 24046226885](https://github.com/tile-ai/TileOPs/actions/runs/24046226885) due to **two independent root causes**:

| Bucket | Cases | Symptom | Root cause |
|---|---|---|---|
| `softmax` / `log_softmax` / `logsumexp` bench | 15 | `AttributeError: Cannot autotune SoftmaxKernel: 'self.kernel' is not set` | `SoftmaxKernel.__init__` calls `init_config(config, tune)` *before* setting `self.kernel`; when `tune=True`, `init_config()` delegates to `autotune()` which requires `self.kernel`. Introduced by #801. |
| GQA / MHA paged decode bench (FA3 baseline) | 6 | `TypeError: flash_attn_with_kvcache() got an unexpected keyword argument 'block_table'` | `flash_attn_interface` renamed its paged-attention kwarg from `block_table` to `page_table`. |

The two issues are independent and split into two commits.

This is a follow-up to #774 (which partially addressed the FA3 rename); the softmax bug landed afterwards via #801 and needed a separate fix.

### `[Fix][Benchmark] Build softmax-family kernels before init_config`

Reorders `SoftmaxKernel` and `LogSumExpKernel` `__init__` to construct `self.kernel` *before* calling `init_config()`. `tile_n` is baked into the kernel at build time, so we pre-build with the heuristic `block_m` from `default_config`. `autotune_configs` is already filtered to a single `tile_n`, so the pre-built kernel matches the search space. If a user-provided `config` selects a `block_m` mapping to a different `tile_n`, the kernel is rebuilt (cheap due to the `lru_cache` on `_softmax_kernel` / `_logsumexp_kernel`).

Adds `tune=True` regression cases to `SoftmaxFixture` / `LogSoftmaxFixture` / `LogSumExpFixture` — existing `tune=False` cases never exercised the broken path, which is how #801 slipped through.

### `[Fix][Benchmark] Rename FA3 paged-decode baseline kwarg block_table to page_table`

Two-line change in `bench_gqa_decode_paged.py` and `bench_mha_decode_paged.py`. Verified the FA3 signature in `tileops-runner:latest` lists `page_table` and no `block_table`.

## Test plan

All verification was done on a local GPU with the upstream `tileops-runner:latest` image and the worktree overlaid on `/home/ci-runner/tileops` so both the bench files **and** the kernel fix are exercised:

- [x] **21 / 21 previously-failing nightly bench cases pass** in `tileops-runner:latest` (3 GQA paged + 3 MHA paged + 5 softmax + 5 log_softmax + 5 logsumexp), 9m19s end-to-end
- [x] **104 / 104** `tests/ops/test_softmax.py -m full` cases pass on host (includes the 3 new `tune=True` regression cases + all pre-existing `tune=False` cases — no regression)
- [x] **15 / 15** `benchmarks/ops/bench_softmax.py` cases pass on host
- [x] FA3 signature inspection in `tileops-runner:latest` confirms `page_table` is the new kwarg
- [x] All pre-commit hooks pass (incl. gitleaks, ruff, codespell)

## Notes

- The 3 new `tune=True` regression params are marked `pytest.mark.full` so the nightly `op_test` job catches the same bug class before it reaches the bench job.
- This PR does **not** modify the manifest or change op interfaces, in line with the trust model.

### CODE REVIEW

File: tileops/kernels/reduction/softmax/logsumexp_fwd.py [hunk 1]
```diff
@@ -248,16 +248,35 @@ def __init__(
...
+        # tile_n is baked into the kernel at build time, so we pre-compute it
+        # from the heuristic block_m (default_config); autotune_configs is
+        # already filtered to only include configs with the same tile_n.
+        self._tile_n = self.default_config["tile_n"]
         self.kernel = _logsumexp_kernel(
             self.M,
             self.N,
             self.dtype_str,
             self._tile_n,
         )
```
[the remark this answers is not in the document]
Comment (superAngGao) [reply tileops/kernels/reduction/softmax/logsumexp_fwd.py:269]: The limitation you describe is real but pre-existing — it is the documented behavior of `autotune_configs` introduced in #801, not something this PR adds. See the explicit filter in `SoftmaxKernel.autotune_configs` / `LogSumExpKernel.autotune_configs`:

```python
# Use the same tile_n that the kernel was built with
tile_n = getattr(self, "_tile_n", self.default_config["tile_n"])
...
# Only include configs compatible with the built kernel's tile_n
if bm_tile_n != tile_n:
    continue
```

This PR is scoped to making the broken `tune=True` path actually run (15 nightly bench cases were raising `AttributeError`); it does not change the autotune search-space design.

Expanding the search to multiple `tile_n` regimes would require building one kernel per regime, autotuning each, and picking the global best — a substantial refactor of the autotune flow that is deliberately deferred. f1be1d0 expands the inline `__init__` comment in both kernels to make this trade-off explicit and tag it as a known follow-up so future readers see why we pre-build with the default `tile_n`.

No functional change in the doc commit.

[the remark this answers is not in the document]
Comment (superAngGao) [reply tileops/kernels/reduction/softmax/logsumexp_fwd.py:269]: Filed #821 to track the cross-`tile_n` autotune exploration as a deferred follow-up. 0e28b15 replaces the prose follow-up note in `__init__` with a direct pointer to that issue, so the deferred work is discoverable from the code site.
