### ISSUE TITLE
[BUG][CI] fix broken moe_fused_topk tests and remove unsound targeted scope

### ISSUE THREAD

**Issue by lcy-seso** [tile-ai/TileOPs#973]
### Symptom / Motivation

PR #970 (`[Refactor][Benchmark] Narrow gen_inputs return types across workload protocols`) unified all workload `gen_inputs()` to return tuples, but missed updating `tests/ops/test_moe_fused_topk.py`. This broke all 13 `test_fused_topk` cases on CI with:

```
AttributeError: 'tuple' object has no attribute 'to'
```

CI failure: https://github.com/tile-ai/TileOPs/actions/runs/24411551409/job/71309490631

Despite `gpu-smoke` being a required status check and **failing** on #970's PR, the PR was merged because the `tileops-review` team had `bypass_mode: pull_request` on the main branch ruleset (ID 8507572).

Separately, the CI targeted scope strategy (introduced in #510 on 2026-03-15) maps `tileops/ops/*.py` changes to only run the corresponding `tests/ops/test_<op>.py`. This is an unsound assumption — ops share code via kernels and utilities, so modifying one op can silently break tests for other ops.

### Root Cause Analysis

1. **Test bug**: `tests/ops/test_moe_fused_topk.py:84` calls `gating = test.gen_inputs()` but `gen_inputs()` now returns `(tensor,)` (a tuple), not a bare tensor. The subsequent `gating.to(torch.float32)` fails with `AttributeError`.

2. **Unsound CI scope**: `.github/workflows/gpu-smoke.yml` lines 270-281 map `tileops/ops/*.py` → targeted scope, running only `tests/ops/test_<op>.py`. This assumes ops are fully independent, which is false — ops share kernels, base classes, and utility code.

3. **Governance gap**: `tileops-review` team had bypass permission on the main branch ruleset, allowing merge with failing required checks. This bypass has been revoked via GitHub UI.

### Related Files

- `tests/ops/test_moe_fused_topk.py`
- `.github/workflows/gpu-smoke.yml`
- `workloads/moe.py`

## Goal

Fix the broken test, remove the unsound `tileops/ops/*.py` targeted scope so op code changes always trigger full-smoke, and document the governance fix (bypass revocation).

## Plan

1. Fix `tests/ops/test_moe_fused_topk.py:84`: change `gating = test.gen_inputs()` to `(gating,) = test.gen_inputs()`
2. Remove `tileops/ops/*.py` targeted mapping from `.github/workflows/gpu-smoke.yml` — op changes now fall through to `*` catch-all → `full-smoke`
3. Verify `tileops-review` bypass on ruleset 8507572 is revoked (done via GitHub UI, not code change)

## Constraints

- Do not modify `workloads/moe.py` — the tuple return type is correct per #970's protocol
- Targeted scope for `tests/ops/test_*.py`-only changes is retained (test files do not import each other)

## Acceptance Criteria

- [ ] AC-1: Modified files pass unit tests
- [ ] AC-2: All 13 `test_fused_topk` cases pass in CI gpu-smoke
- [ ] AC-3: `tileops/ops/*.py` changes trigger `full-smoke` scope (not `targeted`)
- [ ] AC-4: `tests/ops/test_*.py`-only changes still use `targeted` scope
- [ ] AC-5: Ruleset 8507572 `bypass_actors` is empty (no team can bypass required checks)

**Comment by RMLYC** [comment]
Another occurrence of the same regression showed up in Nightly on commit `84fa4b5a7` (`[Refactor][Benchmark] Narrow gen_inputs return types across workload protocols (#970)`).

CI run:
- https://github.com/tile-ai/TileOPs/actions/runs/24418245432/job/71340912453

`op_test` summary:
- `Run full op tests` completed, but pytest reported `13 failed, 2373 passed, 11 skipped`
- all 13 failures are `tests/ops/test_moe_fused_topk.py::test_fused_topk[...]`
- representative error:

```text
AttributeError: 'tuple' object has no attribute 'to'
```

Relevant call chain:
- `workloads/moe.py`: `FusedTopKTest.gen_inputs()` now returns `(torch.randn(...),)`
- `tests/ops/test_moe_fused_topk.py`: `_check()` still does `gating = test.gen_inputs()`
- `fused_topk_torch(gating, ...)` then calls `gating_output.to(torch.float32)` and fails because `gating` is a tuple

Minimal fix proposal for the `op_test` regression:
1. In `tests/ops/test_moe_fused_topk.py`, unpack the workload output explicitly: change `gating = test.gen_inputs()` to `(gating,) = test.gen_inputs()`
2. Keep `workloads/moe.py` unchanged, since the tuple return type matches the refactored workload protocol from #970
3. Re-run `tests/ops/test_moe_fused_topk.py` and confirm all 13 `fused_topk` cases pass in CI

This comment is limited to the `op_test` failure path; benchmark failures from the same Nightly run are separate and were not analyzed here.
